### ISSUE TITLE
stupid

### ISSUE THREAD

**Issue by psauxx** [Skitttyy/Europa-Leaked#6]
this is stupid github is not a platform to rels deop code, even if it's skidded this will prove nonthin expect cause drama. if u rlly wanted to help people, try talkin to the dev and showin him what he did wrong and how he can improve u will never get a name for yourself if u act this way

**Comment by master7720** [comment]
*github is not a platform to rels deop code* xDDDD

**Comment by Skitttyy** [comment]
😭

**Comment by psauxx** [comment]
> _github is not a platform to rels deop code_ xDDDD

Not in that since, i was talking about leak releases in that matter.
